/**
 * SEO ARTEFACT GENERATOR — robots.txt, sitemap.xml and the social cards.
 *
 * These three are derived, not written. The sitemap comes from BUILT_ROUTES
 * filtered through the metadata table, so a route that has no page or no
 * description cannot appear in it, and a page that is added without metadata
 * fails `--check` rather than shipping an orphan. The social cards are 1200×630
 * crops of the photography already on each page.
 *
 *   node scripts/build-seo.mjs           write
 *   node scripts/build-seo.mjs --check   verify the committed files are current
 *
 * Same convention as build-projects.mjs and build-india-map.mjs: the output is
 * committed, and CI checks it has not drifted.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import sharp from 'sharp';
import {
  indexableRoutes, seoByPath, ORIGIN, absolute, OG_SIZE, ROUTE_HERO,
} from '../frontend/src/data/seo.js';
import { media } from '../frontend/src/data/media.js';

const CHECK = process.argv.includes('--check');
const PUBLIC = 'frontend/public';
const problems = [];

/* ------------------------------------------------------------------ robots */

/**
 * `/api/` is the enquiry endpoint — a POST-only surface with nothing to index.
 *
 * `/og/` is NOT disallowed, though it was in the first draft of this file. The
 * social cards live there, and facebookexternalhit, Twitterbot and LinkedIn's
 * scraper all obey robots.txt when fetching og:image — so disallowing that
 * directory would have silently broken every link preview the cards exist to
 * produce. The only cost of leaving it open is that the cards may appear in
 * image search, which is not a cost.
 *
 * Nothing else is disallowed. In particular the built CSS, JS and images under
 * /assets/ are LEFT CRAWLABLE on purpose: Google renders the page to index it,
 * and a site that blocks its own stylesheets and scripts gets indexed as the
 * unstyled, empty shell it can see. That mistake is the single most common way
 * a React site disappears from search.
 */
const robots = `# https://www.robotstxt.org/robotstxt.html
# Generated by scripts/build-seo.mjs — do not edit by hand.

User-agent: *
Allow: /

# POST-only enquiry endpoint. Nothing to index, and a crawl of it is a 405.
Disallow: /api/

# NOTHING ELSE IS BLOCKED, deliberately:
#   /assets/  built CSS and JS. Google renders the page before indexing it, and
#             a site that blocks its own stylesheets is indexed as an unstyled
#             shell. This is the most common way a React site loses its rankings.
#   /og/      social cards. facebookexternalhit, Twitterbot and LinkedIn all obey
#             robots.txt when fetching og:image, so blocking these would break
#             every link preview.

Sitemap: ${ORIGIN}/sitemap.xml
`;

/* ----------------------------------------------------------------- sitemap */

/**
 * Priority and changefreq are advisory and widely ignored, but lastmod is not,
 * so it is the one that has to be honest: it is the date this file was last
 * generated, which is the last time the route table actually changed.
 */
const LASTMOD = '2026-09-06';

const priorityFor = (path) => {
  if (path === '/') return '1.0';
  return path.split('/').filter(Boolean).length === 1 ? '0.8' : '0.6';
};

const urls = indexableRoutes.map((path) => `  <url>
    <loc>${absolute(path)}</loc>
    <lastmod>${LASTMOD}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>${priorityFor(path)}</priority>
  </url>`).join('\n');

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-seo.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

/* -------------------------------------------------------------- social cards */

/* Which photograph fronts each route's card: ROUTE_HERO, the same map the LCP
   preload uses, so a card can never show imagery the page does not. */
const CARD_SOURCE = ROUTE_HERO;

const cardName = (path) => (path === '/' ? 'home' : path.replace(/^\/|\/$/g, '').split('/').pop());

async function buildCards() {
  const dir = join(PUBLIC, 'og');
  if (!CHECK) mkdirSync(dir, { recursive: true });

  for (const path of indexableRoutes) {
    const slug = CARD_SOURCE[path];
    const item = slug ? media[slug] : null;
    if (!item) { problems.push(`no card source for ${path}`); continue; }

    const src = join(PUBLIC, item.src);
    if (!existsSync(src)) { problems.push(`missing source image ${item.src}`); continue; }

    const out = join(dir, `${cardName(path)}.jpg`);
    if (CHECK) {
      if (!existsSync(out)) { problems.push(`missing card ${out}`); continue; }
      const m = await sharp(out).metadata();
      if (m.width !== OG_SIZE.width || m.height !== OG_SIZE.height) {
        problems.push(`card ${out} is ${m.width}x${m.height}, expected ${OG_SIZE.width}x${OG_SIZE.height}`);
      }
      continue;
    }
    await sharp(src)
      .resize(OG_SIZE.width, OG_SIZE.height, { fit: 'cover', position: 'attention' })
      .jpeg({ quality: 78, mozjpeg: true })
      .toFile(out);
  }

  /* The site-wide default, used by anything without its own. */
  const fallback = join(dir, 'vedanjay-power.jpg');
  if (CHECK) {
    if (!existsSync(fallback)) problems.push(`missing default card ${fallback}`);
  } else {
    await sharp(join(PUBLIC, media['hero-primary'].src))
      .resize(OG_SIZE.width, OG_SIZE.height, { fit: 'cover', position: 'attention' })
      .jpeg({ quality: 78, mozjpeg: true })
      .toFile(fallback);
  }
}

/* -------------------------------------------------------------------- run */

const files = [
  [join(PUBLIC, 'robots.txt'), robots],
  [join(PUBLIC, 'sitemap.xml'), sitemap],
];

/* A route in the sitemap that no page serves is the worst failure here, so it
   is checked in both modes rather than only on --check. */
for (const path of indexableRoutes) {
  if (!seoByPath.has(path)) problems.push(`sitemap route ${path} has no metadata`);
}

await buildCards();

for (const [file, content] of files) {
  if (CHECK) {
    const current = existsSync(file) ? readFileSync(file, 'utf8') : null;
    if (current !== content) problems.push(`${file} is out of date — run \`npm run seo\``);
  } else {
    writeFileSync(file, content);
  }
}

if (problems.length) {
  console.error('SEO artefacts FAILED:');
  for (const p of problems) console.error(`  - ${p}`);
  process.exit(1);
}

console.log(CHECK
  ? `SEO artefacts current — ${indexableRoutes.length} routes, ${indexableRoutes.length + 1} cards`
  : `Wrote robots.txt, sitemap.xml (${indexableRoutes.length} routes) and ${indexableRoutes.length + 1} social cards`);
